env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  'prettier/prettier': [
    'error',
    {
      'endOfLine': 'auto',
      'usePrettierrc': true,
    },
  ],
  'react/react-in-jsx-scope': 'off',
}
